name: "GitHub Pages - Rust doc"

on:
  push:
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    uses: darbiadev/.github/.github/workflows/github-pages-rust-doc.yaml@f85fb2104404526f99de918714364ad1d5449f5a
