name: "Rust - Publish to crates.io"

on:
  release:
    types: [ released ]

jobs:
  publish:
    uses: darbiadev/.github/.github/workflows/rust-crates-io-publish.yaml@b0749d50c2f32c5672a7c459f55f39416941c26d # v5.1.0
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
