name: "Rust CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    uses: darbiadev/.github/.github/workflows/rust-lint.yaml@6a6eb74ae11149881c29adf5a5f7af23349c8762 # v9.0.0

  clippy:
    needs: lint
    uses: darbiadev/.github/.github/workflows/rust-clippy.yaml@6a6eb74ae11149881c29adf5a5f7af23349c8762 # v9.0.0

  test:
    needs: clippy
    strategy:
      matrix:
        triple:
          - {
            os: "ubuntu-latest",
            target: "x86_64-unknown-linux-gnu",
          }
          - {
            os: "macOS-latest",
            target: "x86_64-apple-darwin",
          }
          - {
            os: "windows-latest",
            target: "x86_64-pc-windows-msvc",
          }

    uses: darbiadev/.github/.github/workflows/rust-test.yaml@6a6eb74ae11149881c29adf5a5f7af23349c8762 # v9.0.0
    with:
      os: ${{ matrix.triple.os }}
      target: ${{ matrix.triple.target }}

  docs:
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write

    uses: darbiadev/.github/.github/workflows/github-pages-rust-doc.yaml@6a6eb74ae11149881c29adf5a5f7af23349c8762 # v9.0.0
