name: "Rust - Publish to crates.io"

on:
  release:
    types: [ released ]

jobs:
  publish:
    uses: darbiadev/.github/.github/workflows/rust-crates-io-publish.yaml@45471b560aceda922ebec22a20b72f0c29914cad # v15.1.0
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
