name: "Rust - Publish to crates.io"

on:
  release:
    types: [ released ]

jobs:
  publish:
    uses: darbiadev/.github/.github/workflows/rust-crates-io-publish.yaml@440166417b42442c6114aaa895094f0db7de9b78 # v15.2.0
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
